### ISSUE TITLE
Problem on iterating ArrayList

### ISSUE THREAD

**Issue by littmus** [originell/jpype#142]
```
λ ~/venv/ python -V
Python 2.7.9
λ ~/venv/ cat test.py
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())

arr = jpype.java.util.ArrayList()
l = [i for i in arr]
λ ~/venv/source jpype0.5.7/bin/activate
(jpype0.5.7)λ ~/venv/ python test.py
(jpype0.5.7)λ ~/venv/ deactivate
λ ~/venv/source jpype0.6.0/bin/activate
(jpype0.6.0)λ ~/venv/ python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    l = [i for i in arr]
  File "/home/dwshin/venv/jpype0.6.0/local/lib/python2.7/site-packages/jpype/_jcollection.py", line 32, in __next__
    return next(self.iterator)
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121
```

**Comment by Eothred** [comment]
Same (or at least very similar) issue here, using JPype 0.6. Preparing an example would take a while, but I am essentially trying to iterate a Java iterable object. Code worked with earlier versions of JPype.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-44-647246ea3fd7> in <module>()
----> 1 for bpm in Sequence.getAllNodesOfType('BPM'):
      2     print bpm.getPosition()

/home/ylevinse/.local/lib/python2.7/site-packages/jpype/_jcollection.pyc in __next__(self)
     30 
     31     def __next__(self):
---> 32         return next(self.iterator)
     33 
     34     # Compatibility name

RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121
```
