### ISSUE TITLE
error while installing jpype

### ISSUE THREAD

**Issue by nairgokul70** [originell/jpype#185]
I have been trying to install jpype latest version on windows 7 64 bit machine with following

java version "1.7.0_80"
Java(TM) SE Runtime Environment (build1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

I also have microsoft visual C++ 64 bit redistributable being installed. 
below is the error i am getting.
```

collecting jpype1
  Using cached JPype1-0.6.1.tar.gz
Building wheels for collected packages: jpype1
  Running setup.py bdist_wheel for jpype1
  Complete output from command c:\python27\python.exe -c "import setuptools;__fi
le__='c:\\users\\\\appdata\\local\\temp\\pip-build-2lrqdg\\jpype1\\se
tup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exe
c'))" bdist_wheel -d c:\users\appdata\local\temp\tmpvlaj5zpip-wheel-
:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\jpype
  copying jpype\JClassUtil.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\nio.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\reflect.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_core.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_darwin.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_gui.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jarray.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jclass.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jcollection.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jexception.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jobject.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jpackage.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jproxy.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jvmfinder.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_jwrapper.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_linux.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_properties.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_pykeywords.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_refdaemon.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\_windows.py -> build\lib.win-amd64-2.7\jpype
  copying jpype\__init__.py -> build\lib.win-amd64-2.7\jpype
  creating build\lib.win-amd64-2.7\jpype\awt
  copying jpype\awt\__init__.py -> build\lib.win-amd64-2.7\jpype\awt
  creating build\lib.win-amd64-2.7\jpype\awt\event
  copying jpype\awt\event\WindowAdapter.py -> build\lib.win-amd64-2.7\jpype\awt\
event
  copying jpype\awt\event\__init__.py -> build\lib.win-amd64-2.7\jpype\awt\event

  creating build\lib.win-amd64-2.7\jpypex
  copying jpypex\__init__.py -> build\lib.win-amd64-2.7\jpypex
  creating build\lib.win-amd64-2.7\jpypex\swing
  copying jpypex\swing\AbstractAction.py -> build\lib.win-amd64-2.7\jpypex\swing

  copying jpypex\swing\pyutils.py -> build\lib.win-amd64-2.7\jpypex\swing
  copying jpypex\swing\__init__.py -> build\lib.win-amd64-2.7\jpypex\swing
  running build_ext
  building '_jpype' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\\appdata\local\temp\pip-build-2lrqdg\jpype1\setup.
py", line 191, in <module>
      ext_modules=[jpypeLib],
    File "c:\python27\lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 4
9, in run
      _build_ext.run(self)
    File "c:\python27\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\\appdata\local\temp\pip-build-2lrqdg\jpype1\setup.
py", line 155, in build_extensions
      build_ext.build_extensions(self)
    File "c:\python27\lib\distutils\command\build_ext.py", line 448, in build_ex
tensions
      self.build_extension(ext)
    File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 1
74, in build_extension
      _build_ext.build_extension(self, ext)
    File "c:\python27\lib\distutils\command\build_ext.py", line 498, in build_ex
tension
      depends=ext.depends)
    File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
      self.initialize()
    File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
    File "c:\python27\lib\site-packages\setuptools\msvc9_support.py", line 52, i
n query_vcvarsall
      return unpatched['query_vcvarsall'](version, *args, **kwargs)
    File "c:\python27\lib\distutils\msvc9compiler.py", line 299, in query_vcvars
all
      raise ValueError(str(list(result.keys())))
  ValueError: [u'path']

  ----------------------------------------
  Failed building wheel for jpype1
Failed to build jpype1
Installing collected packages: jpype1
  Running setup.py install for jpype1
    Complete output from command c:\python27\python.exe -c "import setuptools, t
okenize;__file__='c:\\users\\appdata\\local\\temp\\pip-build-2lrqdg
\\jpype1\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read(
).replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\gokul~1.n
ai\appdata\local\temp\pip-ujlr58-record\install-record.txt --single-version-exte
rnally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building '_jpype' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\\appdata\local\temp\pip-build-2lrqdg\jpype1\setu
p.py", line 191, in <module>
        ext_modules=[jpypeLib],
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line 6
1, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line
 49, in run
        _build_ext.run(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 339, in run
        

- [ ] self.build_extensions()

      File "c:\users\\appdata\local\temp\pip-build-2lrqdg\jpype1\setu
p.py", line 155, in build_extensions
        build_ext.build_extensions(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 448, in build_
extensions
        self.build_extension(ext)
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line
 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\python27\lib\distutils\command\build_ext.py", line 498, in build_
extension
        depends=ext.depends)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc9_support.py", line 52,
 in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 299, in query_vcva
rsall
        raise ValueError(str(list(result.keys())))
    ValueError: [u'path']

    ----------------------------------------
Command "c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\us
ers\\\\appdata\\local\\temp\\pip-build-2lrqdg\\jpype1\\setup.py';exec
(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),
 __file__, 'exec'))" install --record c:\users\appdata\local\temp\pi
p-ujlr58-record\install-record.txt --single-version-externally-managed --compile
" failed with error code 1 in c:\users\\appdata\local\temp\pip-build-
2lrqdg\jpype1
```

**Comment by marscher** [comment]
https://stackoverflow.com/questions/11267463/compiling-python-modules-on-windows-x64
