### ISSUE TITLE
RuntimeError: No matching overloads found. for subclass

### ISSUE THREAD

**Issue by Sahasrara** [originell/jpype#193]
I've got a class that extends from a super class.  The class files generated are:
LDF1File.class
LDF1File$1.class
LDFFile.class <-- super class

Firstly, I had previously thought $1 classnames were for inner classes, but apparently they can be/are generated for classes extending other classes.  When I try:
LDF1File = JClass('aero.blue.bdms.ldf.stream.LDF1File')

I get java.lang.RuntimeException: Class aero.blue.bdms.ldf.stream.LDF1File not found, whereas:
LDF1FileDollar = JClass('aero.blue.bdms.ldf.stream.LDF1File$1')

succeeds.  However, when I try to instantiate that class (which as a single constructor that takes a string argument, I get:
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    LDF1FileDollar(JString('./ldfs/smaller.ldf'))
  File "/home/eric/Software/anaconda3/envs/blue3/lib/python3.5/site-packages/JPype1-0.6.1-py3.5-linux-x86_64.egg/jpype/_jclass.py", line 86, in _javaInit
    *args)
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:117

**Comment by Sahasrara** [comment]
./jars/mockito-all-1.9.5.jar:./jars/jul-to-slf4j-1.7.6.jar:./jars/bdms-monitoring-lib-1.0.2.jar:./jars/bdms-bdfjava-lib-1.0.8-SNAPSHOT.jar:./jars/bdms-workflow-lib-1.0.6-SNAPSHOT.jar:./jars/logging-core-0.1.6.jar:./jars/spring-core-3.2.3.RELEASE.jar:./jars/spring-test-3.2.3.RELEASE.jar:./jars/commons-compiler-2.6.1.jar:./jars/guava-15.0.jar:./jars/gson-2.2.4.jar:./jars/jcl-over-slf4j-1.7.6.jar:./jars/joda-time-2.3.jar:./jars/spring-context-3.2.3.RELEASE.jar:./jars/spring-web-3.2.3.RELEASE.jar:./jars/junit-4.8.2.jar:./jars/aopalliance-1.0.jar:./jars/spring-expression-3.2.3.RELEASE.jar:./jars/commons-io-1.3.2.jar:./jars/spring-context-support-3.2.3.RELEASE.jar:./jars/spring-beans-3.2.3.RELEASE.jar:./jars/logback-core-1.0.13.jar:./jars/janino-2.6.1.jar:./jars/logback-classic-1.0.13.jar:./jars/spring-webmvc-3.2.3.RELEASE.jar:./jars/commons-logging-1.1.3.jar:./jars/bdms-chunkjava-lib-1.0.9-SNAPSHOT.jar:./jars/spring-aop-3.2.3.RELEASE.jar:./jars/commons-math-2.2.jar:./jars/log4j-over-slf4j-1.7.6.jar:./jars/bdms-chunkjava-lib-1.0.8.jar:./jars/bdms-ldfjava-lib-1.0.9-SNAPSHOT.jar:./jars/aspectjweaver-1.7.0.jar:./jars/slf4j-api-1.7.6.jar
