### ISSUE TITLE
I wanted to rewrote my monkeyrunner script (used workd with Jython) with Python, but it causes an error!

### ISSUE THREAD

**Issue by xiaopantt** [originell/jpype#197]
I want to use python not jython. 
So i import jpype1
# coding: utf8
import os
import jpype
jarpath = os.path.join(os.path.abspath('.'), ur'D:\sdk\tools\lib\monkeyrunner.jar')
jpype.startJVM(jpype.getDefaultJVMPath(), "-ea", "-Djava.class.path=%s" % jarpath)
mkrunner_class = jpype.JClass('com.android.monkeyrunner.MonkeyRunner')
mkrunner = mkrunner_class()
devices = mkrunner.waitForConnection()
jpype.shutdownJVM()

Traceback (most recent call last):
  File "jvm_test.py", line 9, in <module>
    mkrunner = mkrunner_class()
  File "C:\Python27\lib\site-packages\jpype1-0.6.1-py2.7-win32.egg\jpype\_jclass.py", line 86, in _javaInit
    *args)
RuntimeError: No matching overloads found. at native\common\jp_method.cpp:117

what's wrong, can you help?

**Comment by xiaopantt** [comment]
source _jclass.py  method _javaInit 
def _javaInit(self, *args):
    object.__init__(self)
    print "args", args
    if len(args) == 1 and isinstance(args[0], tuple) \
       and args[0][0] is _SPECIAL_CONSTRUCTOR_KEY:
        self.__javaobject__ = args[0][1]
    else:
        self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(
            *args)
I'm not good at Java.  i want to use java monkeyrunner source .

public class MonkeyRunner extends PyObject implements ClassDictInit {
    private static final Logger LOG = Logger.getLogger(MonkeyRunner.class.getCanonicalName());
    private static ChimpChat chimpchat;

    public MonkeyRunner() {
    }
...

**Comment by xiaopantt** [comment]
i use python subprocess rewrited a adb client
