### ISSUE TITLE
docs not updated automatically

### ISSUE THREAD

**Issue by marscher** [originell/jpype#214]
@originell Can you please have a look, why readthedocs.org does not update the documenation automatically?

**Comment by originell** [comment]
@marscher we only have failed builds for quite some time now

<img width="831" alt="screen shot 2017-03-27 at 19 25 42" src="https://cloud.githubusercontent.com/assets/23529/24369085/2b325880-1323-11e7-8749-9fbbc94937f4.png">

Here's the output.

```
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/stable/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/stable/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/stable/local/lib/python2.7/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/stable/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/stable/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 54, in <module>
    import jpype
ImportError: No module named jpype

Exception occurred:
  File "conf.py", line 54, in <module>
    import jpype
ImportError: No module named jpype
The full traceback has been saved in /tmp/sphinx-err-QpPGkb.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>.
```

Any ideas? I'm not quite sure what is happening there.

Also, do you have a readthedocs.org account? I can add you as maintainer there, so you can at least have a look at the build logs.

**Comment by marscher** [comment]
its marscher also on rtd. I can have a look. It seems like the package is not installed in the environment.

**Comment by originell** [comment]
added you there as maintainer. Can you access the logs now?

**Comment by marscher** [comment]
yes. Thank you!

**Comment by originell** [comment]
Thank you for maintaining :)

**Comment by marscher** [comment]
np. Docs are up 2 date again. Thanks for the quick response.
