### ISSUE TITLE
RuntimeError: No matching overloads found. at native\common\jp_method.cpp:117

### ISSUE THREAD

**Issue by gogoda** [originell/jpype#216]
### My python code:
```  
import os
from jpype import *

jarpath = os.path.join(os.path.abspath('.'), 'D:/WORKTOOLS/jarpackage/tech/scaffold/scaffold-boot/1.0.0.0-SNAPSHOT/')
startJVM(getDefaultJVMPath(), "-Djava.ext.dirs=%s" % jarpath)
test_class = JClass("com.ziroom.tech.scaffold.boot.util.security.MD5Util")
jclass = test_class()
data = 'abcd'
sign = jclass.md5Hex(data)
shutdownJVM()
```    
### run error info:
```C:\Python34\python.exe D:/autoTest/PYTHON/just_test/jpypetestfile.py
Traceback (most recent call last):
  File "D:/autoTest/PYTHON/just_test/jpypetestfile.py", line 15, in <module>
    sign = jclass.md5Hex(data)
RuntimeError: No matching overloads found. at native\common\jp_method.cpp:117

**Comment by gogoda** [comment]
### run error info:
```C:\Python34\python.exe D:/autoTest/PYTHON/just_test/jpypetestfile.py
Traceback (most recent call last):
  File "D:/autoTest/PYTHON/just_test/jpypetestfile.py", line 15, in <module>
    sign = jclass.md5Hex(data)
RuntimeError: No matching overloads found. at native\common\jp_method.cpp:117```

**Comment by marscher** [comment]
what is the java prototype of MD5Util.md5Hex?
