### ISSUE TITLE
JArray for JLong going very wrong

### ISSUE THREAD

**Issue by Thrameos** [originell/jpype#285]
I was trying to wrap up the modifications that I made to get pickle working but I was hitting a series of errors so bad the jvm crashed.  I tried a number of methods and eventually rolled back to the master figuring I could find it by rolling forward to locate the error.  Only I got pretty much the same issue going back to the master.

```
jpype.JArray(jpype.JLong,1)([1,2,3,4,5,6,7])[:]
=> array([1, 0, 2, 0, 3, 0, 4])
```

The slice operator is copying the longs into memory which are ints.  The array returned is half the elements (the other half clobbered some piece of memory).  It just so happened that it hit something vital that lead the crash.  We have a test for JLong conversion but it appears to not catch the problem.  

I scanned the patches for anything can could have changed the corresponding section of code, and turned up nothing.  I am now unsure this path ever worked properly.  It may be a windows issue but it would be good to verify.

**Comment by Thrameos** [comment]
Well that would do it....

```

NPY_LONG¶

    Equivalent to either NPY_INT or NPY_LONGLONG, depending on the platform.
```

```
PyObject* JPLongType::getArrayRangeToSequence(jarray a, int lo, int hi) {
    return getSlice<jlong>(a, lo, hi, NPY_LONG, PyLong_FromLong);
}
```

**Comment by marscher** [comment]
So there is a lengths mismatch between jlong and npy_long on 32 bit?

**Comment by marscher** [comment]
I have to admit, that I tested this code only on Linux and hoped my unit tests are strong enough to cover problems on other platforms too. Can you provide a test, which fails on your platform please?

**Comment by Thrameos** [comment]
The current test fails.  But fails so hard the the system segfault 10 tests later.  I will send the patch.  Just changing to NPY_INT64 and adding the extra forward decl fixed it.

**Comment by Thrameos** [comment]
What I do not understand is how it could have ever passed.  But it appears to have worked before.  I will have to check if when the code or test changed.

**Comment by Thrameos** [comment]
The test code is 2 years since the last change and the bug is 4 years since last change.  I know the test passed when I started working on the project thus it must be able to pass incorrectly under some situation.  But I have no clue how that could have ever been the case.  Alternatively something in numpy changed that caused the issue.

I am removing all code that used NPY_LONG and switching to NPY_INT64.  

Pre patch
```
$ python3 -m nose test.jpypetest
F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jpackage.py:35: UserWarning: JVM not started yet, can not inspect JPackage contents
  warnings.warn("JVM not started yet, can not inspect JPackage contents")
..............F........EE.#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000775913d3, pid=6784, tid=0x0000000000001938
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0x313d3]
[error occurred during error reporting (printing problematic frame), id 0xc0000005]

# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# F:\nelson85pl\nelson85\devel\open\jpype\hs_err_pid6784.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

After switching to NPY_INT64

```
$ python3 -m nose test.jpypetest
F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jpackage.py:35: UserWarning: JVM not started yet, can not inspect JPackage contents
  warnings.warn("JVM not started yet, can not inspect JPackage contents")
.......................EE........................................................S.........S.SSSS..............S............................EEE...............
======================================================================
ERROR: testSetFromNPIntArray (test.jpypetest.transplant_class.<locals>.C)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\array.py", line 255, in testSetFromNPIntArray
    a = np.random.randint(-2**31 - 1, 2**31 - 1, size=n).astype(np.int32)
  File "mtrand.pyx", line 984, in mtrand.RandomState.randint
ValueError: low is out of bounds for int32

======================================================================
ERROR: testSetFromNPLongArray (test.jpypetest.transplant_class.<locals>.C)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\array.py", line 266, in testSetFromNPLongArray
    a = np.random.randint(-2**63, 2**63 - 1, size=n).astype(np.int64)
  File "mtrand.pyx", line 984, in mtrand.RandomState.randint
ValueError: low is out of bounds for int32

======================================================================
ERROR: Test multiple proxy calls with different threads at the same time.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\proxy_multithreaded.py", line 133, in testProxyWithMultipleThreadExecutionMultiCallbackInstances
    self.executor = self.package.ProxyExecutor(10)
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jpackage.py", line 60, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package jpype.proxy.ProxyExecutor is not Callable

======================================================================
ERROR: Test multiple proxy calls with different threads at the same time.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\proxy_multithreaded.py", line 104, in testProxyWithMultipleThreadExecutionSingleCallbackInstance
    proxy = JProxy(self.package.TestInterface4, inst=C())
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jproxy.py", line 50, in __init__
    raise TypeError("JProxy requires java interface classes "
TypeError: JProxy requires java interface classes or the names of java interfaces classes

======================================================================
ERROR: Test multiple proxy calls with a single threaded executor.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\proxy_multithreaded.py", line 75, in testProxyWithSingleThreadExecution
    proxy = JProxy(self.package.TestInterface4, inst=C())
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jproxy.py", line 50, in __init__
    raise TypeError("JProxy requires java interface classes "
TypeError: JProxy requires java interface classes or the names of java interfaces classes

----------------------------------------------------------------------
```

After fixing limits on the array test.
```
$ python3 -m nose test.jpypetest
F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jpackage.py:35: UserWarning: JVM not started yet, can not inspect JPackage contents
  warnings.warn("JVM not started yet, can not inspect JPackage contents")
.................................................................................S.........S.SSSS..............S............................EEE...............
======================================================================
ERROR: Test multiple proxy calls with different threads at the same time.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\proxy_multithreaded.py", line 133, in testProxyWithMultipleThreadExecutionMultiCallbackInstances
    self.executor = self.package.ProxyExecutor(10)
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jpackage.py", line 60, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package jpype.proxy.ProxyExecutor is not Callable

======================================================================
ERROR: Test multiple proxy calls with different threads at the same time.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\proxy_multithreaded.py", line 104, in testProxyWithMultipleThreadExecutionSingleCallbackInstance
    proxy = JProxy(self.package.TestInterface4, inst=C())
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jproxy.py", line 50, in __init__
    raise TypeError("JProxy requires java interface classes "
TypeError: JProxy requires java interface classes or the names of java interfaces classes

======================================================================
ERROR: Test multiple proxy calls with a single threaded executor.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\nelson85pl\nelson85\devel\open\jpype\test\jpypetest\proxy_multithreaded.py", line 75, in testProxyWithSingleThreadExecution
    proxy = JProxy(self.package.TestInterface4, inst=C())
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jproxy.py", line 50, in __init__
    raise TypeError("JProxy requires java interface classes "
TypeError: JProxy requires java interface classes or the names of java interfaces classes

----------------------------------------------------------------------
Ran 158 tests in 1.474s

FAILED (SKIP=7, errors=3)
```

Not sure what the issue is on those last 3 tests.  But I will submit the pull request.

**Comment by marscher** [comment]
Thanks for the effort! What was wrong with the integer boundaries?
Shouldn't it be [-2^31 - 1, 2^31-1]

**Comment by Thrameos** [comment]
No integers are not symmetric in twos complement.  [https://en.wikipedia.org/wiki/Signed_number_representations](url)

As it shows in [https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html](url) the maximum int is `2^31-1` and the minimum is `-2^31`.  I am guessing the original code was supposed to say `-(2^31-1)=-2^31+1` which would still be a valid integer.  As it stands npy is giving me a limit error.  

This may be another issue of numpy differences as this error is new but our test is old.

**Comment by marscher** [comment]
I see :)

**Comment by Thrameos** [comment]
Okay those other errors are coming from new tests.  I will see if I can address their issue.
