### ISSUE TITLE
Unable to install JPype1 on Windows

### ISSUE THREAD

**Issue by krlng** [originell/jpype#292]
When I try to install some package which depends on JPype (like JayDeBeApi or pyodbc) I get the following error. I also should mention that I run the shell doing this with the administrator account, so not my actual user. Stacktrace:

```
Building wheels for collected packages: JPype1
  Running setup.py bdist_wheel for JPype1 ... error
  Failed building wheel for JPype1
  Running setup.py clean for JPype1
Failed to build JPype1
Installing collected packages: JPype1, JayDeBeApi
  Running setup.py install for JPype1 ... error
Exception:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 82: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\programdata\anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\programdata\anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\programdata\anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\programdata\anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\programdata\anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 82: invalid start byte
Cache entry deserialization failed, entry ignored
```

**Comment by Thrameos** [comment]
I have not seen this error.  It could be an interaction with the particular version of anaconda.

**Comment by marscher** [comment]
On 22.03.2018 16:02, Karl Nelson wrote:
> I have not seen this error.  It could be an interaction with the particular version of anaconda.
> 

on anaconda you can use conda to install jpype

**Comment by marscher** [comment]
the file can be decoded with utf-8. Unless you tell us exact version numbers in your conda env, we have no chance to reproduce this. Please feel free to re-open this, when you can provide more info or a way to reproduce this.
