### ISSUE TITLE
Fail in proxy test

### ISSUE THREAD

**Issue by Thrameos** [originell/jpype#299]
Proxy test fails in master.

```
$ python -m nose -v test.jpypetest
...
testProtectedMethodPropertyOverlapInvisibleAttribute (test.jpypetest.PropertiesTestCase) ... ok
testPublicMethodPropertyOverlap (test.jpypetest.PropertiesTestCase) ... ok
Test multiple proxy calls with different threads at the same time. ... Fatal Python error: PyEval_SaveThread: NULL tstate
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000003fdff3d93, pid=10700, tid=0x0000000000002a28
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libpython2.7.dll+0x13d93][thread 9856 also had an error]
Aborted
```

or sometimes
```
java.lang.RuntimeException: Python exception thrown: AttributeError: 'JPackage' object has no attribute 'ReturnObject'
        at jpype.JPypeInvocationHandler.hostInvoke(Native Method)
        at jpype.JPypeInvocationHandler.invoke(JPypeInvocationHandler.java:10)
        at com.sun.proxy.$Proxy1.testMethodInt(Unknown Source)
Fatal Python error: This thread state must be current when releasing
        at jpype.proxy.ProxyExecutor$ProxyCaller.call(Unknown Source)
        at jpype.proxy.ProxyExecutor$ProxyCaller.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Aborted
```

Platform is cygwin with latest master.  I know that it passed at some point so it must be a recent error.

**Comment by Thrameos** [comment]
Is this code correct?

```
void* PythonHostEnvironment::prepareCallbackBegin()
{
        PyGILState_STATE state = PyGILState_Ensure();;
        return (void*)new PyGILState_STATE(state);
}

void PythonHostEnvironment::prepareCallbackFinish(void* state)
{
        PyGILState_STATE* state2 = (PyGILState_STATE*)state;
        PyGILState_Release(*state2);
        delete state2;
}
```

It looks really fishy to be deleting set of variables that were taken from C with a C++ delete call.

**Comment by Thrameos** [comment]
No scratch that I missed the `new` call an though the raw state was being passed.  It still looks really off from the idiom and it appear to not be exception safe.

**Comment by Thrameos** [comment]
I think it is bogus to try to take a copy of PyGILState_STATE.  It is explicit in the documentation that the object is an opaque object thus we shouldn't be copying it.

**Comment by marscher** [comment]
right.

**Comment by Thrameos** [comment]
I need to check some more platforms on this one.  I think the particular error I am getting may be related to compiler switches as I have one copy of cygwin working perfectly and another copy failing miserably.   This does match a previously reported error in threading so it must be a real issue.  I am just puzzled how to solve it.
